### ISSUE TITLE
patch 86: not working

### ISSUE THREAD

**Issue by lidel97** [seraphinush-gaming/block-list#3]
patch 86, block-list module does not work

**Comment by ElToupet** [comment]
/ ! \ This is a workaround, not the developper's doing / ! \

The last version of S_LOGIN.def is 14, mod uses 12 or 13.
So you can update mod with editing "index.js"

the line : 'S_LOGIN', mod.majorPatchVersion >= 81 ? 13 : 12
I'm not into coding at all, just so you know, but i'd say, it indicates to use S_LOGIN.13 as long as game client version is, or over 81, or else, use S_LOGIN.12.

So, just changing to ">=86 ? 14 : 13" do the trick.

**Comment by ElToupet** [comment]
> 
> 
> patch 86, block-list module does not work

/ ! \ This is a workaround, not the developper's doing / ! \

The last version of S_LOGIN.xx.def is 14, mod uses 12 or 13.
So you can update mod with editing "index.js"

the line : 'S_LOGIN', mod.majorPatchVersion >= 81 ? 13 : 12
I'm not into coding at all, just so you know, but i'd say, it indicates to use S_LOGIN.13 as long as game client version is, or over 81, or else, use S_LOGIN.12.

So, just changing to ">=86 ? 14 : 13" do the trick.

**Comment by lidel97** [comment]
done as suggested, then i have to stop autoupdate, otherwise it updates and then won't work. btw ty for the reply, if i stop autoupdate, block list works again. one more thing: the system says " block list has been synchronized, please relog to synchronized user memo". i follow the instructions but memo is not synchronized with what i filled in the memo section. i have a character in which i have typed some memos in the blocked players, but this memo is not synchronized with my other characters, only the block list. any suggest?

**Comment by ElToupet** [comment]
- update, yeah, once you modify manually a file you have to disable auto-update or it'll get the source file again and overwrite what you did. (check if there are any update regulary, some mods can do crap with doing such rubbish edits XD)

 - list... Indeed i also had issues with trying to sync list for other chars, even if i took a base one, and then tried to get it on the other chars it felt.. kind of random, often overwrite database with the logged char (i guess i was not doing it right)... So in the end, i just take a base list, export it, and then import it with other chars...
Don't forget to export everytime you add/remove a blocked user.
And as for memo... idk how it works, but i also don't get the little bit of text suposed to be there :(

**Comment by notseraphh** [comment]
I'll look into it over the weekend.
